### ISSUE TITLE
feature: auto-extend config textbox length to fit content when opening/refreshing website 

### ISSUE THREAD

**Issue by rszyma** [jtroo/jtroo.github.io#3]
e.g. [this link](https://jtroo.github.io/?data=BQEwpgZgzgTgxgAgIYIEYMSAlAKFJAGyQE8wY0kowcEFgB7AOzAFooALegFwQEYAGQQgJQIXLGgw06UAO4BLLnHbTawEWIkaeEJAQJd2MegFcA5itq0A3NeQgQCALb0YYZFATMw4EADoA1ToiAy09HT0DI1MLIOAJdRIyFll2eQJWdjACR0YkADcJVDckAGtpXFw8cAgiUnI8-OkAfWFIHhh5Cx5mnCwAH0Gh4ZH+kAAuAGkwYgBBBC5xgHYEEymZ+cWAZgAOAE4ECeniABEF8d4AVgAmBBwjmYBhc62DtePnxf2dw-XiACFzksfjh3jNAYtLgAWLarP5nRZ7QT8IA) opens kanata simulator with larger config that doesn't fit within default textbox size, while another half of screen (on 1920x1080 at least) is unoccupied.

**Comment by jtroo** [comment]
Hopefully done in https://github.com/jtroo/jtroo.github.io/commit/003173dc48331ce78c76782333fb94a3861feb50
